### ISSUE TITLE
Add templates for mails sent during KWoC

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/mailing-scripts#2]
### Refer the following points to add them according to the convention set for templates:

- Follow the guidelines in [about templates](https://github.com/kossiitkgp/mailing-scripts/blob/main/templates/README.md).
- See [selections templates](https://github.com/kossiitkgp/mailing-scripts/tree/main/templates/selections) for already existing examples.
- Update [varaible_mappings.py](https://github.com/kossiitkgp/mailing-scripts/blob/main/templates/variable_mappings.py)

## TODO
We send the following mails during KWoC, hence templates in [templates](https://github.com/kossiitkgp/mailing-scripts/tree/main/templates/) are required to created.
  - [ ] To previous participants, that KWoC is back
  - [ ] Mid evals deadline reminder
  - [ ] Mid evals
    - [ ] Qualified
    - [ ] Disqualified
  - [ ] End evals deadline reminder
  - [ ] End evals
    - [ ] Disqualified
    - [ ] Mail with certificates' link to qualified contributors
    - Top Contributor with their swag details, if any, and certificate link - try to add a template, but this mail is highly probable to change every year..

**Comment by proffapt** [comment]
Being implemented in #5
